No screenshot for android and fix pipeline
ittagnelli/snAcks pull request #96
Opened 2022-05-04 10:14 UTC by Andrea-Canale

Ricreata la pipeline e rimossa la possibilità di fare screenshot su Android

2022-05-04 13:10 UTC, mancusoa74 commented
nella pipeline per PWA non puoi cancellare tutto con rm -rf * perchè elimini anche la cartella charts.
devi cambiare comando in modo che non venga eliminata la directory charts

sshpass -p ${{ secrets.SCP_PASSWD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_CONNSTRING }} -p22 "cd snacks && rm -rf *"

2022-05-04 13:51 UTC, Andrea-Canale commented
ora dovrebbe essere funzionante

2022-05-04 19:30 UTC, mancusoa74 requested changes
man rf

2022-05-05 10:08 UTC, mancusoa74 approved these changes

2022-05-05 10:08 UTC, merged